#!/bin/bash

# CONTRIBUTION
## Author: Tom Sapletta
## Created Date: 26.05.2022

## EXAMPLE
# ./apifork.sh install
# ./apifork.sh update
# ./apifork.sh remove

# CONFIG
CMD=$1
[ -z "$CMD" ] && CMD="install"
#
PROJECT_FILE=$2
# zapisz domyslnie do .apifork gdy podano plik konfiguracyjny
[ ! -z "$PROJECT_FILE" ] && echo "$PROJECT_FILE" > ".apifork"
# gdy brak podanego pliku konfiguracyjnego
[ -z "$PROJECT_FILE" ] && PROJECT_FILE="apifork.txt"

[ -z "$PROJECT_LIST" ] && PROJECT_LIST=$(cat ".apifork")
# START
# If the last line of your file has no newline on the end
while git_repo=; IFS=$' \t\r\n' read -r git_repo || [[ $git_repo ]]; do
  repo=($git_repo)
  echo "$CMD PROJECT: ${repo[1]}/  FROM REPO:  (${repo[0]})"
  if [ "$CMD" == "install" ]; then
    echo "${repo[1]}" >>.gitignore
    git clone ${git_repo}
  elif [ "$CMD" == "update" ]; then
    cd ${repo[1]} && git pull
    cd ..
  elif [ "$CMD" == "remove" ]; then
    rm -rf ${repo[1]}
  else
    echo "Command $CMD is not recognized"
  fi
done <"$PROJECT_LIST"
